# This file is part of a Spipu Bundle
#
# (c) Laurent Minguet
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
services:
    # API Services
    # You can add fixtures. They must implement FixtureInterface and have the spipu.fixture tag
    # You must implement DefinitionInterface to define the menu
    spipu.ui.service.menu_definition:
        class: Spipu\UiBundle\Service\Menu\Definition

    Spipu\UiBundle\Service\Ui\GridFactory:
        autowire: true
        arguments:
            $container: '@service_container'

    Spipu\UiBundle\Service\Ui\FormFactory:
        autowire: true
        arguments:
            $container: '@service_container'

    Spipu\UiBundle\Service\Ui\ShowFactory:
        autowire: true

    Spipu\UiBundle\Form\Options\ActiveStatus:
        public: true
        autowire: true

    Spipu\UiBundle\Form\Options\BooleanStatus:
        public: true
        autowire: true

    Spipu\UiBundle\Form\Options\YesNo:
        public: true
        autowire: true

    Spipu\UiBundle\Service\Menu\Manager:
        arguments:
           - "@security.authorization_checker"
           - "@spipu.ui.service.menu_definition"

    Spipu\UiBundle\Twig\OptionsExtension:
        autowire: true
        tags: ["twig.extension"]
        arguments:
            - "@service_container"

    Spipu\UiBundle\Twig\UiExtension:
        autowire: true
        tags: ["twig.extension"]

    Spipu\UiBundle\Service\Ui\Grid\DataProvider\Doctrine:
        public: true
        autowire: true

    # Assets
    Spipu\UiBundle\Assets\Bootstrap:
        autowire: true
        tags: ['spipu.asset']

    Spipu\UiBundle\Assets\FontAwesome:
        autowire: true
        tags: ['spipu.asset']

    Spipu\UiBundle\Assets\Jquery:
        autowire: true
        tags: ['spipu.asset']

    Spipu\UiBundle\Assets\Popper:
        autowire: true
        tags: ['spipu.asset']
